import { 
  Home, 
  RefreshCw as RefreshCwIcon,
  FileText as FileTextIcon, 
  Target, 
  Bell, 
  GitBranch, 
  BarChart3, 
  Settings,
  Plus,
  Search,
  Filter,
  Calendar,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  X,
  Check,
  AlertCircle,
  Info,
  CheckCircle,
  XCircle,
  Loader,
  Menu,
  Moon,
  Sun,
  LogOut,
  User,
  Edit,
  Trash2,
  Copy,
  Download,
  Upload,
  RefreshCw,
  ExternalLink,
  Link,
  Clock,
  TrendingUp,
  TrendingDown,
  Flame,
  Award,
  Trophy,
  Star,
  Heart,
  MessageCircle,
  Send,
  Bot,
  Sparkles,
  Zap,
  Layers,
  Database,
  Cloud,
  CloudOff,
  Wifi,
  WifiOff,
  Battery,
  BatteryCharging,
  Maximize,
  Minimize,
  MoreHorizontal,
  MoreVertical,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  Key,
  Mail,
  Phone,
  MapPin,
  CalendarDays,
  Hash,
  Tag,
  Bookmark,
  Flag,
  AlertTriangle,
  Shield,
  ShieldCheck,
  Activity,
  BarChart,
  PieChart,
  LineChart,
  Sprout,
  Leaf,
  TreePine,
  Flower2,
  Sunrise,
  Sunset,
  Keyboard,
  HelpCircle,
  Share2,
  BookmarkPlus,
  Save,
  FolderOpen,
  FilePlus,
  FileCheck,
  Inbox,
  SendHorizontal,
  Paperclip,
  Smile,
  ThumbsUp,
  ThumbsDown,
  MessageSquare,
  Users,
  UserPlus,
  UserCheck,
  UserX,
  Building,
  Briefcase,
  GraduationCap,
  Lightbulb,
  BookOpen,
  BookMarked,
  Code,
  Terminal,
  GitMerge,
  GitPullRequest,
  GitCommit,
  Package,
  Box,
  Container,
  Cpu,
  HardDrive,
  Server,
  Monitor,
  Smartphone,
  Tablet,
  Laptop,
  Tv,
  Speaker,
  Volume2,
  VolumeX,
  BellRing,
  Camera,
  Image,
  Video,
  Music,
  Headphones,
  Mic,
  MicOff,
  Play,
  Pause,
  SkipBack,
  SkipForward,
  Repeat,
  Shuffle,
  List,
  Grid,
  LayoutGrid,
  ListOrdered,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  Highlighter,
  Eraser,
  Type,
  SunMedium,
  AtSign,
  Percent,
  Calculator,
  Scale,
  Globe,
  Map,
  Navigation,
  Compass,
  Anchor,
  Plane,
  Car,
  Bike,
  Footprints,
  Building2,
  Hospital,
  School,
  University,
  Store,
  ShoppingCart,
  CreditCard,
  Wallet,
  Gift,
  Gem,
  Crown,
  Medal,
  Ribbon,
  Scroll,
  Feather,
  PenTool,
  Pen,
  Pencil,
  Ruler,
  Triangle,
  Circle,
  Square,
  Hexagon,
  Octagon,
  Pentagon,
  Diamond,
  Asterisk,
  Cross,
  PlusCircle,
  MinusCircle,
  Equal,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  ArrowUpLeft,
  ArrowDownRight,
  ArrowDownLeft,
  ChevronsUp,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight,
  CornerDownLeft,
  CornerDownRight,
  CornerLeftUp,
  CornerLeftDown,
  CornerRightUp,
  CornerRightDown,
  Move,
  Maximize2,
  Minimize2,
  ZoomIn,
  ZoomOut,
  Crosshair,
  Focus,
  CircleDot,
  Clipboard,
  ClipboardCheck,
  ClipboardList,
  ClipboardPaste,
  StickyNote,
  File,
  Folder,
  FolderPlus,
  FolderMinus,
  Archive,
  Snowflake,
  Umbrella,
  CloudSun,
  CloudMoon,
  CloudSnow,
  CloudLightning,
  CloudFog,
  Wind,
  Droplets,
  Thermometer,
  Sun as SunIcon,
  Moon as MoonIcon,
  Cloud as CloudIcon,
  Flame as FireIcon,
  TrendingUp as TrendUpIcon,
  Star as StarIcon,
  FileText,
} from 'lucide-react';
import type { LucideProps } from 'lucide-react';
import type { FC } from 'react';

const iconMap = {
  home: Home,
  'file-text': FileTextIcon,
  target: Target,
  bell: Bell,
  'git-branch': GitBranch,
  'bar-chart': BarChart3,
  settings: Settings,
  plus: Plus,
  search: Search,
  filter: Filter,
  calendar: Calendar,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  x: X,
  check: Check,
  'alert-circle': AlertCircle,
  info: Info,
  'check-circle': CheckCircle,
  'x-circle': XCircle,
  loader: Loader,
  menu: Menu,
  moon: Moon,
  sun: Sun,
  'log-out': LogOut,
  user: User,
  edit: Edit,
  trash: Trash2,
  copy: Copy,
  download: Download,
  upload: Upload,
  refresh: RefreshCwIcon,
  'external-link': ExternalLink,
  link: Link,
  clock: Clock,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  flame: Flame,
  award: Award,
  trophy: Trophy,
  star: Star,
  heart: Heart,
  'message-circle': MessageCircle,
  send: Send,
  bot: Bot,
  sparkles: Sparkles,
  zap: Zap,
  layers: Layers,
  database: Database,
  cloud: Cloud,
  'cloud-off': CloudOff,
  wifi: Wifi,
  'wifi-off': WifiOff,
  battery: Battery,
  'battery-charging': BatteryCharging,
  maximize: Maximize,
  minimize: Minimize,
  'more-horizontal': MoreHorizontal,
  'more-vertical': MoreVertical,
  eye: Eye,
  'eye-off': EyeOff,
  lock: Lock,
  unlock: Unlock,
  key: Key,
  mail: Mail,
  phone: Phone,
  'map-pin': MapPin,
  'calendar-days': CalendarDays,
  hash: Hash,
  tag: Tag,
  bookmark: Bookmark,
  flag: Flag,
  'alert-triangle': AlertTriangle,
  shield: Shield,
  'shield-check': ShieldCheck,
  activity: Activity,
  'bar-chart-3': BarChart,
  'pie-chart': PieChart,
  'line-chart': LineChart,
  sprout: Sprout,
  leaf: Leaf,
  'tree-pine': TreePine,
  flower: Flower2,
  sunrise: Sunrise,
  sunset: Sunset,
  keyboard: Keyboard,
  'help-circle': HelpCircle,
  share: Share2,
  bookmarkplus: BookmarkPlus,
  save: Save,
  folderopen: FolderOpen,
  fileplus: FilePlus,
  filecheck: FileCheck,
  inbox: Inbox,
  sendhorizontal: SendHorizontal,
  paperclip: Paperclip,
  smile: Smile,
  thumbsup: ThumbsUp,
  thumbsdown: ThumbsDown,
  messagesquare: MessageSquare,
  users: Users,
  userplus: UserPlus,
  usercheck: UserCheck,
  userx: UserX,
  building: Building,
  briefcase: Briefcase,
  graduationcap: GraduationCap,
  lightbulb: Lightbulb,
  bookopen: BookOpen,
  bookmarked: BookMarked,
  code: Code,
  terminal: Terminal,
  gitmerge: GitMerge,
  gitpullrequest: GitPullRequest,
  gitcommit: GitCommit,
  package: Package,
  box: Box,
  container: Container,
  cpu: Cpu,
  harddrive: HardDrive,
  server: Server,
  monitor: Monitor,
  smartphone: Smartphone,
  tablet: Tablet,
  laptop: Laptop,
  tv: Tv,
  speaker: Speaker,
  volume2: Volume2,
  volumeX: VolumeX,
  bellring: BellRing,
  camera: Camera,
  image: Image,
  video: Video,
  music: Music,
  headphones: Headphones,
  mic: Mic,
  micOff: MicOff,
  play: Play,
  pause: Pause,
  skipback: SkipBack,
  skipforward: SkipForward,
  repeat: Repeat,
  shuffle: Shuffle,
  list: List,
  grid: Grid,
  layoutgrid: LayoutGrid,
  listordered: ListOrdered,
  bold: Bold,
  italic: Italic,
  underline: Underline,
  strikethrough: Strikethrough,
  highlighter: Highlighter,
  eraser: Eraser,
  type: Type,
  sunmedium: SunMedium,
  atsign: AtSign,
  percent: Percent,
  calculator: Calculator,
  scale: Scale,
  globe: Globe,
  map: Map,
  navigation: Navigation,
  compass: Compass,
  anchor: Anchor,
  plane: Plane,
  car: Car,
  bike: Bike,
  footprints: Footprints,
  building2: Building2,
  hospital: Hospital,
  school: School,
  university: University,
  store: Store,
  shoppingcart: ShoppingCart,
  creditcard: CreditCard,
  wallet: Wallet,
  gift: Gift,
  gem: Gem,
  crown: Crown,
  medal: Medal,
  ribbon: Ribbon,
  scroll: Scroll,
  feather: Feather,
  pentool: PenTool,
  pen: Pen,
  pencil: Pencil,
  ruler: Ruler,
  triangle: Triangle,
  circle: Circle,
  square: Square,
  hexagon: Hexagon,
  octagon: Octagon,
  pentagon: Pentagon,
  diamond: Diamond,
  asterisk: Asterisk,
  cross: Cross,
  pluscircle: PlusCircle,
  minuscircle: MinusCircle,
  equal: Equal,
  arrowup: ArrowUp,
  arrowdown: ArrowDown,
  arrowleft: ArrowLeft,
  arrowright: ArrowRight,
  arrowupright: ArrowUpRight,
  arrowupleft: ArrowUpLeft,
  arrowdownright: ArrowDownRight,
  arrowdownleft: ArrowDownLeft,
  chevronsup: ChevronsUp,
  chevronsdown: ChevronsDown,
  chevronsleft: ChevronsLeft,
  chevronsright: ChevronsRight,
  cornerdownleft: CornerDownLeft,
  cornerdownright: CornerDownRight,
  cornerleftup: CornerLeftUp,
  cornerleftdown: CornerLeftDown,
  cornerrightup: CornerRightUp,
  cornerrightdown: CornerRightDown,
  move: Move,
  maximize2: Maximize2,
  minimize2: Minimize2,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
  crosshair: Crosshair,
  focus: Focus,
  circledot: CircleDot,
  clipboard: Clipboard,
  clipboardcheck: ClipboardCheck,
  clipboardlist: ClipboardList,
  clipboardpaste: ClipboardPaste,
  stickynote: StickyNote,
  file: File,
  folder: Folder,
  folderplus: FolderPlus,
  folderminus: FolderMinus,
  archive: Archive,
  snowflake: Snowflake,
  umbrella: Umbrella,
  cloudsun: CloudSun,
  cloudmoon: CloudMoon,
  cloudsnow: CloudSnow,
  cloudlightning: CloudLightning,
  cloudfog: CloudFog,
  wind: Wind,
  droplets: Droplets,
  thermometer: Thermometer,
};

export type IconName = keyof typeof iconMap;

export interface IconProps extends Omit<LucideProps, 'ref'> {
  name: IconName;
  size?: number | string;
}

export const Icon: FC<IconProps> = ({ name, size = 20, ...props }) => {
  const IconComponent = iconMap[name] || iconMap['alert-circle'];
  
  if (!IconComponent) {
    return null;
  }
  
  return <IconComponent size={size} {...props} />;
};

export default Icon;
